{% set name = "dimod" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dimod-{{ version }}.tar.gz
  sha256: c8a708d44f4b811360ba3bdda537aaeeb3ec847a092492ddf822aa02d98f6be7

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - cython >=0.29.21,<3.0
    - numpy >=1.20.0,<2.0.0
    - pip
    - python
    - setuptools >=46.4.0
    - wheel
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - dimod
    - dimod.testing
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dwavesystems/dimod
  summary: A shared API for binary quadratic model samplers.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - BastianZim
